"""
ews_report.py
=============
Bilingual (Arabic / English) Expert Reports for the Early Warning System.

Produces three artifacts from a finalized EWS diagnosis:
  1. report_text_en  -- plain-text English narrative
  2. report_text_ar  -- plain-text Arabic narrative 
  3. report_html     -- a self-contained Jinja2-rendered HTML page
"""

from typing import Any, Dict, List, Optional

try:
    from jinja2 import Environment, BaseLoader, select_autoescape
    _HAS_JINJA = True
except ImportError:
    _HAS_JINJA = False

class EwsReportPayload:
    def __init__(
        self,
        area_name: str,
        area_id: int,
        risk_level: str,
        stress_probability: float,
        action: str,
        action_ar: str,
        reasoning: List[str],
        reasoning_ar: List[str],
        shap_explanation: Dict[str, Any]
    ):
        self.area_name = area_name
        self.area_id = area_id
        self.risk_level = risk_level
        self.stress_probability = stress_probability
        self.action = action
        self.action_ar = action_ar
        self.reasoning = reasoning
        self.reasoning_ar = reasoning_ar
        self.shap_explanation = shap_explanation

def build_text_en(p: EwsReportPayload) -> str:
    lines = []
    lines.append(f"EARLY WARNING SYSTEM REPORT")
    lines.append(f"Target Protected Area: {p.area_name} (ID: {p.area_id})")
    lines.append(f"Risk Level: {p.risk_level.upper()}")
    lines.append(f"Stress Probability: {p.stress_probability:.1%}")
    lines.append("-" * 40)
    lines.append("")
    lines.append("CONTEXT & OBJECTIVE:")
    lines.append("This report is generated by the AgriMind AI Early Warning System using multi-modal machine learning fusion. It aims to provide an accurate ecological assessment to detect and prevent drought and vegetation stress in Egyptian Protected Areas.")
    lines.append("")
    lines.append("1. DETECTED STRESS INDICATORS:")
    if p.reasoning:
        for r in p.reasoning:
            lines.append(f"  [!] {r}")
    else:
        lines.append("  [✓] No critical stress indicator triggers detected. The area's telemetry shows stable conditions.")
    
    lines.append("")
    lines.append("2. RECOMMENDED MITIGATION STRATEGIES:")
    lines.append(f"  • Primary Action: {p.action}")
    lines.append("  • Additional Guidelines: Ensure routine ecological audits and adhere to the Ministry of Environment's water preservation directives. Maintain continuous satellite telemetry monitoring for early deviation detection.")
    
    if p.shap_explanation and p.shap_explanation.get("feature_impacts"):
        lines.append("")
        lines.append("3. ENVIRONMENTAL DRIVERS (SHAP AI EXPLANATION):")
        lines.append("The following environmental factors have the highest impact on the calculated stress probability:")
        for impact in p.shap_explanation["feature_impacts"][:5]:
            sign = "+" if impact["shap_value"] >= 0 else ""
            feature_name = str(impact['feature']).replace('_', ' ').title()
            lines.append(f"  • {feature_name}:")
            lines.append(f"      Current Value : {impact['feature_value']:.3f}")
            lines.append(f"      Model Impact  : {sign}{impact['shap_value']:.4f}")
            
    return "\n".join(lines)

def build_text_ar(p: EwsReportPayload) -> str:
    lines = []
    lines.append(f"تقرير نظام الإنذار المبكر")
    lines.append(f"المحمية المستهدفة: {p.area_name} (معرف: {p.area_id})")
    risk_ar_map = {
        "Low": "منخفض",
        "Moderate": "متوسط",
        "High": "مرتفع",
        "Critical": "حرج"
    }
    risk_ar = risk_ar_map.get(p.risk_level, p.risk_level)
    lines.append(f"مستوى الخطر: {risk_ar}")
    lines.append(f"احتمالية الإجهاد: {p.stress_probability:.1%}")
    lines.append("-" * 40)
    lines.append("")
    lines.append("السياق والهدف:")
    lines.append("تم إنشاء هذا التقرير بواسطة نظام الإنذار المبكر (AgriMind) المعتمد على الذكاء الاصطناعي وخوارزميات دمج البيانات. يهدف هذا النظام إلى توفير تقييم بيئي دقيق لاكتشاف والوقاية من الجفاف والإجهاد النباتي في المحميات الطبيعية المصرية.")
    lines.append("")
    lines.append("1. مؤشرات الإجهاد المرصودة:")
    if p.reasoning_ar:
        for r in p.reasoning_ar:
            lines.append(f"  [!] {r}")
    else:
        lines.append("  [✓] لا توجد مؤشرات إجهاد حرجة. قراءات المحمية البيئية مستقرة وطبيعية.")
    
    lines.append("")
    lines.append("2. استراتيجيات التخفيف والإجراءات الموصى بها:")
    lines.append(f"  • الإجراء الأساسي: {p.action_ar}")
    lines.append("  • إرشادات إضافية: يُنصح بالالتزام بتوجيهات وزارة البيئة لترشيد وتأمين الموارد المائية، والاستمرار في المراقبة الدورية عبر الأقمار الصناعية لضمان التدخل السريع عند أي تغيرات مناخية طارئة.")
    
    if p.shap_explanation and p.shap_explanation.get("feature_impacts"):
        lines.append("")
        lines.append("3. العوامل البيئية الأكثر تأثيراً (تحليل الذكاء الاصطناعي SHAP):")
        lines.append("يوضح هذا القسم العوامل المناخية والبيئية التي ساهمت بأكبر قدر في حساب احتمالية الإجهاد:")
        for impact in p.shap_explanation["feature_impacts"][:5]:
            sign = "+" if impact["shap_value"] >= 0 else ""
            feature_name = str(impact['feature']).replace('_', ' ').title()
            lines.append(f"  • {feature_name}:")
            lines.append(f"      القيمة الحالية : {impact['feature_value']:.3f}")
            lines.append(f"      تأثير النموذج  : {sign}{impact['shap_value']:.4f}")
            
    return "\n".join(lines)

HTML_TEMPLATE = r"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>EWS Report: {{ p.area_name }}</title>
<style>
  :root {
    --bg: #0f172a; /* slate-900 */
    --card: #1e293b; /* slate-800 */
    --ink: #f8fafc; /* slate-50 */
    --muted: #94a3b8; /* slate-400 */
    --accent: #10b981; /* emerald-500 */
    --warn: #f59e0b; /* amber-500 */
    --crit: #ef4444; /* red-500 */
    --border: #334155; /* slate-700 */
    --primary: #059669;
  }
  body {
    margin: 0; padding: 32px;
    font-family: 'Segoe UI', system-ui, sans-serif;
    background: var(--bg); color: var(--ink); line-height: 1.6;
  }
  .wrap { max-width: 1200px; margin: 0 auto; }
  header { display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid var(--border); padding-bottom: 20px; margin-bottom: 24px; }
  h1 { margin: 0; font-size: 28px; font-weight: 700; color: #fff; }
  h2 { margin: 0 0 16px; font-size: 18px; text-transform: uppercase; letter-spacing: 1px; color: var(--accent); font-weight: 700; border-bottom: 1px solid var(--border); padding-bottom: 8px;}
  .subtle { color: var(--muted); font-size: 14px; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
  .panel { background: var(--card); border: 1px solid var(--border); border-radius: 16px; padding: 24px; box-shadow: 0 4px 20px rgba(0,0,0,0.2); }
  .ar { direction: rtl; text-align: right; font-family: "Tahoma", "Arial", sans-serif; }
  .badge { display: inline-block; padding: 6px 16px; border-radius: 999px; font-size: 13px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.5px; }
  .b-Low { background: rgba(16,185,129,0.2); color: var(--accent); border: 1px solid rgba(16,185,129,0.3); }
  .b-Moderate { background: rgba(245,158,11,0.2); color: var(--warn); border: 1px solid rgba(245,158,11,0.3); }
  .b-High { background: rgba(249,115,22,0.2); color: #f97316; border: 1px solid rgba(249,115,22,0.3); }
  .b-Critical { background: rgba(239,68,68,0.2); color: var(--crit); border: 1px solid rgba(239,68,68,0.3); }
  ul { padding-left: 20px; margin: 12px 0; list-style-type: square; }
  .ar ul { padding-left: 0; padding-right: 20px; }
  li { margin-bottom: 8px; color: #e2e8f0; }
  .stat-box { display: flex; justify-content: space-between; align-items: center; background: rgba(255,255,255,0.03); padding: 12px 16px; border-radius: 8px; margin-bottom: 8px; border: 1px solid rgba(255,255,255,0.05); }
  .stat-val { font-family: monospace; font-weight: bold; font-size: 16px; color: #fff;}
  .impact-pos { color: var(--crit); font-weight: bold; }
  .impact-neg { color: var(--accent); font-weight: bold; }
  p { margin-top: 0; color: #cbd5e1; }
  @media (max-width: 850px) { .grid { grid-template-columns: 1fr; } }
</style>
</head>
<body>
<div class="wrap">
  <header>
    <div>
      <h1>{{ p.area_name }} <span class="subtle">(ID: {{ p.area_id }})</span></h1>
      <div class="subtle" style="margin-top: 4px;">Comprehensive Eco-Stress Evaluation Report</div>
    </div>
    <div style="text-align: right;">
      <div style="margin-bottom: 8px;"><span class="badge b-{{ p.risk_level }}">{{ p.risk_level }} Risk</span></div>
      <div class="subtle">Stress Probability: <strong>{{ "%.1f"|format(p.stress_probability*100) }}%</strong></div>
    </div>
  </header>

  <div class="grid">
    <!-- ENGLISH PANEL -->
    <div class="panel">
      <h2>Context & Objective</h2>
      <p>This report is generated by the AgriMind AI Early Warning System using multi-modal machine learning fusion. It provides an accurate ecological assessment to detect and prevent drought and vegetation stress in Egyptian Protected Areas.</p>

      <h2>1. Detected Stress Indicators</h2>
      {% if p.reasoning %}
      <ul>
        {% for r in p.reasoning %}
        <li>{{ r }}</li>
        {% endfor %}
      </ul>
      {% else %}
      <div class="stat-box" style="color: var(--accent); border-color: rgba(16,185,129,0.3); background: rgba(16,185,129,0.05);">
        [✓] No critical stress indicator triggers detected. Telemetry shows stable conditions.
      </div>
      {% endif %}

      <h2 style="margin-top: 24px;">2. Recommended Mitigation Strategies</h2>
      <div class="stat-box" style="display: block;">
        <strong>Primary Action:</strong><br/>
        <span style="color: #93c5fd;">{{ p.action }}</span>
      </div>
      <p style="font-size: 13px; margin-top: 12px;"><strong>Guidelines:</strong> Ensure routine ecological audits and adhere to the Ministry of Environment's water preservation directives. Maintain continuous satellite telemetry monitoring.</p>

      {% if p.shap_explanation and p.shap_explanation.feature_impacts %}
      <h2 style="margin-top: 24px;">3. Environmental Drivers (SHAP AI)</h2>
      <p style="font-size: 13px;">The following factors have the highest impact on the stress probability:</p>
      {% for impact in p.shap_explanation.feature_impacts[:5] %}
      <div class="stat-box" style="display: block;">
        <div style="display: flex; justify-content: space-between;">
          <strong style="text-transform: capitalize;">{{ impact.feature.replace('_', ' ') }}</strong>
          <span class="{% if impact.shap_value >= 0 %}impact-pos{% else %}impact-neg{% endif %}">
            Impact: {% if impact.shap_value >= 0 %}+{% endif %}{{ "%.4f"|format(impact.shap_value) }}
          </span>
        </div>
        <div style="font-size: 12px; color: var(--muted); margin-top: 4px;">Current Value: {{ "%.3f"|format(impact.feature_value) }}</div>
      </div>
      {% endfor %}
      {% endif %}
    </div>

    <!-- ARABIC PANEL -->
    <div class="panel ar">
      <h2>السياق والهدف</h2>
      <p>تم إنشاء هذا التقرير بواسطة نظام الإنذار المبكر (AgriMind) المعتمد على الذكاء الاصطناعي وخوارزميات دمج البيانات. يهدف النظام إلى توفير تقييم بيئي دقيق لاكتشاف والوقاية من الجفاف والإجهاد النباتي.</p>

      <h2>1. مؤشرات الإجهاد المرصودة</h2>
      {% if p.reasoning_ar %}
      <ul>
        {% for r in p.reasoning_ar %}
        <li>{{ r }}</li>
        {% endfor %}
      </ul>
      {% else %}
      <div class="stat-box" style="color: var(--accent); border-color: rgba(16,185,129,0.3); background: rgba(16,185,129,0.05);">
        [✓] لا توجد مؤشرات إجهاد حرجة. قراءات المحمية البيئية مستقرة وطبيعية.
      </div>
      {% endif %}

      <h2 style="margin-top: 24px;">2. استراتيجيات التخفيف والتوصيات</h2>
      <div class="stat-box" style="display: block;">
        <strong>الإجراء الأساسي:</strong><br/>
        <span style="color: #93c5fd;">{{ p.action_ar }}</span>
      </div>
      <p style="font-size: 13px; margin-top: 12px;"><strong>إرشادات إضافية:</strong> يُنصح بالالتزام بتوجيهات وزارة البيئة لترشيد وتأمين الموارد المائية، والاستمرار في المراقبة الدورية عبر الأقمار الصناعية.</p>

      {% if p.shap_explanation and p.shap_explanation.feature_impacts %}
      <h2 style="margin-top: 24px;">3. العوامل البيئية المؤثرة (SHAP)</h2>
      <p style="font-size: 13px;">العوامل المناخية والبيئية التي ساهمت بأكبر قدر في حساب احتمالية الإجهاد:</p>
      {% for impact in p.shap_explanation.feature_impacts[:5] %}
      <div class="stat-box" style="display: block;">
        <div style="display: flex; justify-content: space-between;">
          <strong style="text-transform: capitalize;">{{ impact.feature.replace('_', ' ') }}</strong>
          <span class="{% if impact.shap_value >= 0 %}impact-pos{% else %}impact-neg{% endif %}">
            التأثير: {% if impact.shap_value >= 0 %}+{% endif %}{{ "%.4f"|format(impact.shap_value) }}
          </span>
        </div>
        <div style="font-size: 12px; color: var(--muted); margin-top: 4px;">القيمة الحالية: {{ "%.3f"|format(impact.feature_value) }}</div>
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>

  <footer class="subtle" style="margin-top:32px; text-align:center; border-top: 1px solid var(--border); padding-top: 16px;">
    Generated securely by AgriMind AI - Early Warning System v2.3
  </footer>
</div>
</body>
</html>
"""

def build_html(p: EwsReportPayload, text_en: str, text_ar: str) -> str:
    if not _HAS_JINJA:
        return (f"<html><body><h1>{p.area_name}</h1>"
                f"<pre>{text_en}</pre>"
                f"<pre dir='rtl'>{text_ar}</pre></body></html>")
    env = Environment(loader=BaseLoader(), autoescape=select_autoescape(["html", "xml"]))
    tpl = env.from_string(HTML_TEMPLATE)
    return tpl.render(p=p, text_en=text_en, text_ar=text_ar)

def render_full_report(p: EwsReportPayload) -> Dict[str, str]:
    en = build_text_en(p)
    ar = build_text_ar(p)
    html = build_html(p, en, ar)
    return {"text_en": en, "text_ar": ar, "html": html}
