/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldRouteImport } from './routes/yield'
import { Route as SoilRouteImport } from './routes/soil'
import { Route as EwsRouteImport } from './routes/ews'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'

const YieldRoute = YieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilRoute = SoilRouteImport.update({
  id: '/soil',
  path: '/soil',
  getParentRoute: () => rootRouteImport,
} as any)
const EwsRoute = EwsRouteImport.update({
  id: '/ews',
  path: '/ews',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/ews': typeof EwsRoute
  '/soil': typeof SoilRoute
  '/yield': typeof YieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/ews': typeof EwsRoute
  '/soil': typeof SoilRoute
  '/yield': typeof YieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/ews': typeof EwsRoute
  '/soil': typeof SoilRoute
  '/yield': typeof YieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/chat'
    | '/dashboard'
    | '/ews'
    | '/soil'
    | '/yield'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyze' | '/chat' | '/dashboard' | '/ews' | '/soil' | '/yield'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/chat'
    | '/dashboard'
    | '/ews'
    | '/soil'
    | '/yield'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  EwsRoute: typeof EwsRoute
  SoilRoute: typeof SoilRoute
  YieldRoute: typeof YieldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield': {
      id: '/yield'
      path: '/yield'
      fullPath: '/yield'
      preLoaderRoute: typeof YieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil': {
      id: '/soil'
      path: '/soil'
      fullPath: '/soil'
      preLoaderRoute: typeof SoilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ews': {
      id: '/ews'
      path: '/ews'
      fullPath: '/ews'
      preLoaderRoute: typeof EwsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  EwsRoute: EwsRoute,
  SoilRoute: SoilRoute,
  YieldRoute: YieldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
